Update index.md
botblock/botblock.github.io pull request #3
Opened 2020-04-10 16:44 UTC by Andre601

2020-04-10 16:59 UTC, Andre601 commented
This PR improves the main page under https://docs.botblock.org, adding stuff like the other libraries available on the BotBlock organisation (as suggested in #1) and other sources.

If any of the libraries have some API docs or similar that should be linked towards, let me know and I add them.

(Also, what's with those backslashes? are they really needed)

2020-04-10 22:48 UTC, MattIPv4 requested changes

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +Home of GitHub Pages on the [BotBlock GitHub org](https://github.com/botblock).
```suggestion
Home of GitHub Pages sites on the [BotBlock GitHub org](https://github.com/botblock).
```
`GitHub Pages` is essentially singular here, so we should use `sites` to clarify that it is referring to the plural.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +## Pages
```suggestion
```

This heading feels incredibly pointless.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* [Main Website](https://botblock.org)
```suggestion
- [Main Website](https://botblock.org)
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +### Libraries
```suggestion
## Libraries

```
Use h2 for headers, linebreak after header.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* BLAPI ([Repo](https://github.com/botblock/BLAPI)\) - Typescript
```suggestion
- BLAPI ([Repo](https://github.com/botblock/BLAPI)\) - Typescript
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* BotList ([Repo](https://github.com/botblock/BotList)\) - JavaScript
```suggestion
- BotList ([Repo](https://github.com/botblock/BotList)\) - JavaScript
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* BotListAPI ([Repo](https://github.com/botblock/BotListAPI)\) - C#
```suggestion
- BotListAPI ([Repo](https://github.com/botblock/BotListAPI)\) - C#
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* discordlists.py ([Repo](https://github.com/botblock/discordlists.py)\) - Python
```suggestion
- discordlists.py ([Repo](https://github.com/botblock/discordlists.py)\) - Python
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
```suggestion
- [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +### Other pages
```suggestion
## Others

```
Use h2 for headings, linebreak after headings. These aren't really pages, so using the more generic `Others` seems more correct.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* [BotBlock.org](https://github.com/botblock/BotBlock.org) - Source code of https://botblock.org
```suggestion
- [BotBlock.org](https://github.com/botblock/BotBlock.org) - Source code of https://botblock.org
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on README.md
> +* [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to do
```suggestion
- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to follow
```
Use `-` for lists. You `follow` a best practice, you don't `do` a best practice.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +Home of GitHub Pages on the [BotBlock GitHub org](https://github.com/botblock).
```suggestion
Home of GitHub Pages sites on the [BotBlock GitHub org](https://github.com/botblock).
```
`GitHub Pages` is essentially singular here, so we should use `sites` to clarify that it is referring to the plural.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +## Libraries
```suggestion
## Libraries

```
Linebreak after heading.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* BLAPI ([Repo](https://github.com/botblock/BLAPI)\) - Typescript
```suggestion
- BLAPI ([Repo](https://github.com/botblock/BLAPI)\) - Typescript
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* BotList ([Repo](https://github.com/botblock/BotList)\) - JavaScript
```suggestion
- BotList ([Repo](https://github.com/botblock/BotList)\) - JavaScript
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* BotListAPI ([Repo](https://github.com/botblock/BotListAPI)\) - C#
```suggestion
- BotListAPI ([Repo](https://github.com/botblock/BotListAPI)\) - C#
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* discordlists.py ([Repo](https://github.com/botblock/discordlists.py)\) - Python
```suggestion
- discordlists.py ([Repo](https://github.com/botblock/discordlists.py)\) - Python
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
```suggestion
- [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +## Other pages
```suggestion
## Others

```
Linebreak after headings. These aren't really pages, so using the more generic `Others` seems more correct.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* [BotBlock.org](https://github.com/botblock/BotBlock.org) - Source code of https://botblock.org
```suggestion
- [BotBlock.org](https://github.com/botblock/BotBlock.org) - Source code of https://botblock.org
```
Use `-` for lists.

2020-04-10 22:48 UTC, MattIPv4 commented on index.md
> +* [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to do
```suggestion
- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to follow
```
Use `-` for lists. You `follow` a best practice, you don't `do` a best practice.

2020-04-10 22:49 UTC, advaith1 commented on README.md
> +Home of GitHub Pages on the [BotBlock GitHub org](https://github.com/botblock).
Is there a point of removing "This is the home for"? We could just not edit this line

2020-04-10 22:50 UTC, MattIPv4 commented on README.md
> +Home of GitHub Pages on the [BotBlock GitHub org](https://github.com/botblock).
More concise, so I think the change might as well be included.

2020-04-10 22:51 UTC, Andre601 commented on README.md
> +* [Main Website](https://botblock.org)
To be fair here: Advaith used * so I just kept this style.

2020-04-10 22:52 UTC, MattIPv4 commented on README.md
> +* [Main Website](https://botblock.org)
Yeah, the existing usage was inconsistent. Might as well fix it whilst we're making changes :)

2020-04-10 22:57 UTC, Andre601 commented
This should be all requested changes...

2020-04-27 00:09 UTC, Andre601 commented
Is that good now @MattIPv4 ?

2020-04-27 08:02 UTC, MattIPv4 requested changes

2020-04-27 08:02 UTC, MattIPv4 commented on README.md
> +- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to do
```suggestion
- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to follow
```
You `follow` a best practice, you don't `do` a best practice.

2020-04-27 08:02 UTC, MattIPv4 commented on index.md
> +- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to do
```suggestion
- [Discord Bot List Best Practices](https://botblock.org/lists/best-practices) ([Repo](https://github.com/botblock/discord-botlist-best-practices)\) - Best practices for bot lists to follow
```
You `follow` a best practice, you don't `do` a best practice.

2020-05-22 10:29 UTC, Andre601 commented
Are there any more changes I should make or is this fine now?

2020-05-22 10:31 UTC, MattIPv4 approved these changes
Lgtm, had forgotten about this

2020-05-22 10:31 UTC, Andre601 commented on README.md
> +- [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
I assume just putting `JavaBotBlockAPI` instead of the full URL would also do the trick here?
Would imo be easier than having the full domain.

2020-05-22 10:32 UTC, MattIPv4 commented on README.md
> +- [JavaBotBlockAPI](https://docs.botblock.org/JavaBotBlockAPI) ([Repo](https://github.com/botblock/JavaBotBlockAPI)\) - Java
Having the full domain is cleaner. Also, not everyone may be accessing this doc from `docs.botblock.org`

2020-05-22 10:32 UTC, merged